services:
  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U opencut" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - opencut-network
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - opencut-network
  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - "8079:80"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - opencut-network
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
        UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
        NEXT_PUBLIC_BETTER_AUTH_URL: ${NEXT_PUBLIC_BETTER_AUTH_URL}
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
      serverless-redis-http:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - opencut-network
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    expose:
      - 80
    restart: unless-stopped
    networks:
      - opencut-network
    depends_on:
      - web
volumes:
  postgres_data:


networks:
  default:
    name: opencut-network
  opencut-network:
    driver: bridge
