FROM nginx:stable-alpine

# Copy custom nginx configuration
COPY config/nginx.conf /etc/nginx/nginx.conf

# Copy HTML files
COPY html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]